version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  coffee-api:
    build:
      context: .
    environment:
      - "DATABASE_PASSWORD=postgres"
    ports:
      - "8080:8080"

volumes:
  pgdata: