spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

---

spring:
  profiles:
    active: local

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/db}
    username: postgres
    password: ${DATABASE_PASSWORD}

