spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

---

spring:
  profiles:
    active: local

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/db}
    username: postgres
    password: ${DATABASE_PASSWORD}

external:
  api:
    customers:
      base-url: https://gorest.co.in
      all-customers-endpoint: /public/v2/users

